import type { Locale } from "@/lib/i18n/types";

export type HomeCopy = {
  atelier: string; hero1: string; hero2: string; heroBody: string; begin: string; tryOn: string;
  feeling: string; place: string; imagined: string; word: string; oneWord: string; continue: string;
  voiceKicker: string; voiceIntro: string; voices: { title: string; body: string }[];
  material1: string; material2: string; materialBody: string;
  steps: { title: string; body: string }[];
  interpretationKicker: string; interpretation1: string; interpretation2: string; interpretation3: string;
  interpretationBody: string; seeInterpretation: string; portraitName: string; portraitTheme: string; quote: string;
  roseGold: string; brilliant: string; pave: string; tryJewel: string; collection: string;
  footerBody: string; footerAtelier: string; footerContact: string; atelierNav: string[]; contactNav: string[];
};

const en: HomeCopy = {
  atelier:"Atelier",hero1:"Your identity.",hero2:"Your jewel.",heroBody:"A private atelier for bespoke jewellery, authored by artificial intelligence and made precious by the person who wears it.",begin:"Begin your reading",tryOn:"Virtual try-on",
  feeling:"A feeling, a memory, a gesture",place:"A place that feels like home",imagined:"Real or imagined",word:"Your most personal word",oneWord:"One word only",continue:"Continue",
  voiceKicker:"02 — Voice",voiceIntro:"Choose the aesthetic language of your jewel.",voices:[{title:"Minimal",body:""},{title:"Romantic",body:"Softness held in precious metal. A feeling made permanent."},{title:"Bold",body:""}],
  material1:"Identity becomes",material2:"a material language.",materialBody:"A Stylix ring is not purchased. It is authored.",
  steps:[{title:"Personal symbols",body:"We begin where language ends. Your memories, textures, zodiac, lifestyle and private references become the grammar of your ring."},{title:"Identity made visible",body:"The AI Jewelry Stylist and GPT conversation transform what you carry inside into precise form — proportion, stone, finish, weight."}],
  interpretationKicker:"03 — Interpretation",interpretation1:"An interpretation",interpretation2:"written for",interpretation3:"the jewel.",interpretationBody:"Every jewel we create arrives with a text — a poetic interpretation of your signals, written in the voice of the ring itself. Not a description. A portrait.",seeInterpretation:"See a full interpretation",portraitName:"Lunar Architect",portraitTheme:"Moonlight",quote:"She constructs silence the way an architect designs with light — each absence as deliberate as presence. The stone holds a room she has not yet entered.",roseGold:"Rose Gold",brilliant:"Round Brilliant",pave:"Pavé Band",tryJewel:"Try your jewel",collection:"View the collection",
  footerBody:"A private atelier for bespoke jewellery — authored by artificial intelligence, made precious by the person who wears it.",footerAtelier:"Atelier",footerContact:"Contact",atelierNav:["Our Process","Materials","Journal","About"],contactNav:["Private Consultation","Custom Orders","Virtual Try-On","Client Profile"],
};

const zh: HomeCopy = {
  atelier:"私人定制",hero1:"你的身份。",hero2:"你的珠宝。",heroBody:"一间由人工智能参与创作的私人珠宝工坊，因佩戴它的人而变得珍贵。",begin:"开始身份解读",tryOn:"虚拟试戴",
  feeling:"一种感受，一段记忆，一个动作",place:"一个让你感到归属的地方",imagined:"真实或想象",word:"最属于你的一个词",oneWord:"只写一个词",continue:"继续",
  voiceKicker:"02 — 风格语言",voiceIntro:"选择属于你的珠宝美学语言。",voices:[{title:"极简",body:""},{title:"浪漫",body:"柔软被珍贵金属承载，让感受成为永恒。"},{title:"大胆",body:""}],
  material1:"让身份成为",material2:"一种材质语言。",materialBody:"Stylix 戒指不是被购买，而是由你创作。",
  steps:[{title:"个人符号",body:"我们从语言结束的地方开始。你的记忆、触感、星座、生活方式与私密线索，构成戒指的语法。"},{title:"让身份被看见",body:"AI 珠宝造型师与 GPT 对话，将你内在的线索转化为精确形态——比例、宝石、表面与重量。"}],
  interpretationKicker:"03 — 解读",interpretation1:"一段解读",interpretation2:"为这件珠宝",interpretation3:"而写。",interpretationBody:"我们创作的每件珠宝都附有一段文字——以珠宝自身的声音，对你的信号作诗意解读。它不是描述，而是一幅肖像。",seeInterpretation:"查看完整解读",portraitName:"月光建筑师",portraitTheme:"月光",quote:"她构筑静默，如建筑师用光作画——每一处留白，都与存在同样经过深思。宝石守着一间她尚未踏入的房间。",roseGold:"玫瑰金",brilliant:"圆形明亮式切割",pave:"密镶戒臂",tryJewel:"试戴你的珠宝",collection:"查看系列",
  footerBody:"一间由人工智能参与创作的私人珠宝工坊，因佩戴它的人而变得珍贵。",footerAtelier:"工坊",footerContact:"联系",atelierNav:["创作流程","材质","日志","关于"],contactNav:["私人咨询","定制订单","虚拟试戴","客户档案"],
};

const fr: HomeCopy = {...en,atelier:"Atelier",hero1:"Votre identité.",hero2:"Votre bijou.",heroBody:"Un atelier privé de joaillerie sur mesure, imaginé avec l’intelligence artificielle et rendu précieux par la personne qui le porte.",begin:"Commencer votre lecture",tryOn:"Essayage virtuel",feeling:"Une sensation, un souvenir, un geste",place:"Un lieu qui ressemble à chez soi",imagined:"Réel ou imaginé",word:"Votre mot le plus personnel",oneWord:"Un seul mot",continue:"Continuer",voiceKicker:"02 — Voix",voiceIntro:"Choisissez le langage esthétique de votre bijou.",voices:[{title:"Minimal",body:""},{title:"Romantique",body:"La douceur retenue dans un métal précieux. Une émotion rendue permanente."},{title:"Audacieux",body:""}],material1:"L’identité devient",material2:"un langage matériel.",materialBody:"Une bague Stylix ne s’achète pas. Elle s’écrit.",steps:[{title:"Symboles personnels",body:"Nous commençons là où les mots s’arrêtent. Vos souvenirs, textures, signe astrologique et références intimes deviennent la grammaire de votre bague."},{title:"L’identité rendue visible",body:"Le styliste joaillier IA et la conversation GPT transforment votre monde intérieur en forme précise — proportion, pierre, finition et poids."}],interpretationKicker:"03 — Interprétation",interpretation1:"Une interprétation",interpretation2:"écrite pour",interpretation3:"le bijou.",interpretationBody:"Chaque bijou arrive avec un texte : une interprétation poétique de vos signes, écrite dans la voix de la bague. Pas une description. Un portrait.",seeInterpretation:"Voir l’interprétation complète",tryJewel:"Essayez votre bijou",collection:"Voir la collection",footerBody:"Un atelier privé de joaillerie sur mesure, imaginé avec l’intelligence artificielle et rendu précieux par la personne qui le porte.",footerContact:"Contact",atelierNav:["Notre processus","Matières","Journal","À propos"],contactNav:["Consultation privée","Commandes sur mesure","Essayage virtuel","Profil client"]};
const es: HomeCopy = {...en,hero1:"Tu identidad.",hero2:"Tu joya.",heroBody:"Un atelier privado de joyería a medida, creado con inteligencia artificial y hecho precioso por quien lo lleva.",begin:"Comienza tu lectura",tryOn:"Prueba virtual",feeling:"Una sensación, un recuerdo, un gesto",place:"Un lugar que se siente como hogar",imagined:"Real o imaginado",word:"Tu palabra más personal",oneWord:"Una sola palabra",continue:"Continuar",voiceKicker:"02 — Voz",voiceIntro:"Elige el lenguaje estético de tu joya.",voices:[{title:"Minimalista",body:""},{title:"Romántico",body:"Suavidad contenida en metal precioso. Una emoción hecha permanente."},{title:"Audaz",body:""}],material1:"La identidad se convierte",material2:"en un lenguaje material.",materialBody:"Un anillo Stylix no se compra. Se crea.",steps:[{title:"Símbolos personales",body:"Comenzamos donde termina el lenguaje. Tus recuerdos, texturas, signo, estilo de vida y referencias privadas forman la gramática de tu anillo."},{title:"La identidad visible",body:"El estilista de joyería con IA y la conversación GPT convierten tu interior en una forma precisa: proporción, piedra, acabado y peso."}],interpretationKicker:"03 — Interpretación",interpretation1:"Una interpretación",interpretation2:"escrita para",interpretation3:"la joya.",interpretationBody:"Cada joya llega con un texto: una interpretación poética de tus señales, escrita con la voz del propio anillo. No una descripción. Un retrato.",seeInterpretation:"Ver la interpretación completa",tryJewel:"Prueba tu joya",collection:"Ver la colección",footerBody:"Un atelier privado de joyería a medida, creado con inteligencia artificial y hecho precioso por quien lo lleva.",footerAtelier:"Atelier",footerContact:"Contacto",atelierNav:["Nuestro proceso","Materiales","Diario","Nosotros"],contactNav:["Consulta privada","Pedidos personalizados","Prueba virtual","Perfil del cliente"]};
const de: HomeCopy = {...en,hero1:"Ihre Identität.",hero2:"Ihr Schmuckstück.",heroBody:"Ein privates Atelier für maßgefertigten Schmuck — mit künstlicher Intelligenz entworfen und durch den Menschen, der ihn trägt, kostbar gemacht.",begin:"Identitätsanalyse beginnen",tryOn:"Virtuelle Anprobe",feeling:"Ein Gefühl, eine Erinnerung, eine Geste",place:"Ein Ort, der sich wie Zuhause anfühlt",imagined:"Real oder vorgestellt",word:"Ihr persönlichstes Wort",oneWord:"Nur ein Wort",continue:"Weiter",voiceKicker:"02 — Ausdruck",voiceIntro:"Wählen Sie die ästhetische Sprache Ihres Schmuckstücks.",voices:[{title:"Minimal",body:""},{title:"Romantisch",body:"Sanftheit in kostbarem Metall. Ein Gefühl, dauerhaft gemacht."},{title:"Kühn",body:""}],material1:"Identität wird",material2:"zur materiellen Sprache.",materialBody:"Ein Stylix-Ring wird nicht gekauft. Er wird gestaltet.",steps:[{title:"Persönliche Symbole",body:"Wir beginnen dort, wo Sprache endet. Erinnerungen, Texturen, Sternzeichen, Lebensstil und private Bezüge werden zur Grammatik Ihres Rings."},{title:"Identität wird sichtbar",body:"KI-Schmuckstylist und GPT-Dialog übersetzen Ihr Inneres in präzise Form — Proportion, Stein, Finish und Gewicht."}],interpretationKicker:"03 — Interpretation",interpretation1:"Eine Interpretation",interpretation2:"geschrieben für",interpretation3:"das Schmuckstück.",interpretationBody:"Jedes Schmuckstück erhält einen Text — eine poetische Deutung Ihrer Signale, erzählt mit der Stimme des Rings. Keine Beschreibung. Ein Porträt.",seeInterpretation:"Vollständige Interpretation",tryJewel:"Schmuckstück anprobieren",collection:"Kollektion ansehen",footerBody:"Ein privates Atelier für maßgefertigten Schmuck — mit künstlicher Intelligenz entworfen und durch den Menschen, der ihn trägt, kostbar gemacht.",footerContact:"Kontakt",atelierNav:["Unser Prozess","Materialien","Journal","Über uns"],contactNav:["Private Beratung","Sonderanfertigungen","Virtuelle Anprobe","Kundenprofil"]};
const ja: HomeCopy = {...en,atelier:"アトリエ",hero1:"あなたの個性。",hero2:"あなたのジュエリー。",heroBody:"人工知能とともに創り、身につける人によって価値を宿す、ビスポークジュエリーのためのプライベートアトリエ。",begin:"診断を始める",tryOn:"バーチャル試着",feeling:"感情、記憶、しぐさ",place:"故郷のように感じる場所",imagined:"現実でも、想像でも",word:"あなたを表す最も個人的な言葉",oneWord:"ひとつだけ",continue:"続ける",voiceKicker:"02 — 表現",voiceIntro:"ジュエリーの美意識を選んでください。",voices:[{title:"ミニマル",body:""},{title:"ロマンティック",body:"貴金属に宿る柔らかさ。感情を永遠の形へ。"},{title:"ボールド",body:""}],material1:"個性は",material2:"素材の言語になる。",materialBody:"Stylixのリングは買うものではなく、あなたが創るもの。",steps:[{title:"個人のシンボル",body:"言葉が終わる場所から始めます。記憶、質感、星座、暮らし、密かな手がかりがリングの文法になります。"},{title:"個性を可視化",body:"AIジュエリースタイリストとGPTの対話が、内面を比率、石、仕上げ、重さという精密な形へ変換します。"}],interpretationKicker:"03 — 解釈",interpretation1:"ひとつの解釈を",interpretation2:"ジュエリーのために",interpretation3:"綴る。",interpretationBody:"すべてのジュエリーには、リング自身の声であなたのサインを詩的に読み解く文章が添えられます。説明ではなく、肖像です。",seeInterpretation:"全文を読む",tryJewel:"ジュエリーを試着",collection:"コレクションを見る",footerBody:"人工知能とともに創り、身につける人によって価値を宿す、ビスポークジュエリーのためのプライベートアトリエ。",footerAtelier:"アトリエ",footerContact:"お問い合わせ",atelierNav:["制作プロセス","素材","ジャーナル","私たちについて"],contactNav:["個別相談","カスタムオーダー","バーチャル試着","顧客プロフィール"]};
const ko: HomeCopy = {...en,atelier:"아틀리에",hero1:"당신의 정체성.",hero2:"당신의 주얼리.",heroBody:"인공지능과 함께 만들고 착용하는 사람으로 인해 소중해지는 비스포크 주얼리 프라이빗 아틀리에.",begin:"정체성 리딩 시작",tryOn:"가상 착용",feeling:"느낌, 기억, 몸짓",place:"집처럼 느껴지는 장소",imagined:"실재하거나 상상한",word:"가장 개인적인 단어",oneWord:"단 하나의 단어",continue:"계속",voiceKicker:"02 — 표현",voiceIntro:"주얼리의 미학적 언어를 선택하세요.",voices:[{title:"미니멀",body:""},{title:"로맨틱",body:"귀금속에 담긴 부드러움. 감정을 영원한 형태로."},{title:"볼드",body:""}],material1:"정체성은",material2:"소재의 언어가 됩니다.",materialBody:"Stylix 링은 구매하는 것이 아니라 직접 창작하는 것입니다.",steps:[{title:"개인적인 상징",body:"언어가 끝나는 곳에서 시작합니다. 기억, 질감, 별자리, 라이프스타일과 개인적 단서가 반지의 문법이 됩니다."},{title:"보이는 정체성",body:"AI 주얼리 스타일리스트와 GPT 대화가 내면을 비율, 스톤, 마감, 무게라는 정교한 형태로 바꿉니다."}],interpretationKicker:"03 — 해석",interpretation1:"하나의 해석을",interpretation2:"주얼리를 위해",interpretation3:"씁니다.",interpretationBody:"모든 주얼리에는 반지 자신의 목소리로 당신의 신호를 시적으로 해석한 글이 함께합니다. 설명이 아닌 초상입니다.",seeInterpretation:"전체 해석 보기",tryJewel:"주얼리 착용하기",collection:"컬렉션 보기",footerBody:"인공지능과 함께 만들고 착용하는 사람으로 인해 소중해지는 비스포크 주얼리 프라이빗 아틀리에.",footerAtelier:"아틀리에",footerContact:"문의",atelierNav:["제작 과정","소재","저널","소개"],contactNav:["프라이빗 상담","커스텀 주문","가상 착용","고객 프로필"]};
const ar: HomeCopy = {...en,atelier:"المشغل",hero1:"هويتك.",hero2:"جوهرتك.",heroBody:"مشغل خاص للمجوهرات المصممة حسب الطلب، تصوغها تقنيات الذكاء الاصطناعي وتمنحها قيمتها الشخصية التي ترتديها.",begin:"ابدأ قراءة هويتك",tryOn:"التجربة الافتراضية",feeling:"إحساس، ذكرى، إيماءة",place:"مكان يشبه الوطن",imagined:"حقيقي أو متخيّل",word:"كلمتك الأكثر خصوصية",oneWord:"كلمة واحدة فقط",continue:"متابعة",voiceKicker:"02 — الأسلوب",voiceIntro:"اختر اللغة الجمالية لجوهرتك.",voices:[{title:"بسيط",body:""},{title:"رومانسي",body:"نعومة يحتضنها معدن نفيس. شعور يتحول إلى أثر دائم."},{title:"جريء",body:""}],material1:"تتحول الهوية إلى",material2:"لغة مادية.",materialBody:"خاتم Stylix لا يُشترى، بل يُؤلَّف.",steps:[{title:"رموز شخصية",body:"نبدأ حيث تنتهي الكلمات. ذكرياتك وملامسك وبرجك وأسلوب حياتك وإشاراتك الخاصة تصبح قواعد خاتمك."},{title:"هوية مرئية",body:"يحوّل مصمم المجوهرات بالذكاء الاصطناعي وحوار GPT ما بداخلك إلى شكل دقيق: النسبة والحجر والتشطيب والوزن."}],interpretationKicker:"03 — التأويل",interpretation1:"تأويل",interpretation2:"كُتب من أجل",interpretation3:"الجوهرة.",interpretationBody:"تصل كل جوهرة بنص يفسر إشاراتك شعريًا بصوت الخاتم نفسه. ليست وصفًا، بل صورة شخصية.",seeInterpretation:"اقرأ التأويل الكامل",tryJewel:"جرّب جوهرتك",collection:"شاهد المجموعة",footerBody:"مشغل خاص للمجوهرات المصممة حسب الطلب، تصوغها تقنيات الذكاء الاصطناعي وتمنحها قيمتها الشخصية التي ترتديها.",footerAtelier:"المشغل",footerContact:"تواصل",atelierNav:["مسارنا","المواد","المجلة","من نحن"],contactNav:["استشارة خاصة","طلبات مخصصة","تجربة افتراضية","ملف العميل"]};

export const homeCopy: Record<Locale, HomeCopy> = { en, zh, fr, es, de, ja, ko, ar };
