import type { Locale } from '@/lib/i18n/types';

const en = ['FOUNDING DROP 01','Concept preview','Build the piece we make first.','Your choices will shape our first production sample.','Choose the foundation','Your base','Select up to five','Your symbols','Choose at least one symbol','Estimated founding price','03 / Set the signal','Would you actually wear this?','This is a research preview, not a stocked product. Join the founding list to vote for the first sample and receive the launch offer only if we produce it.','Open the full design studio','What feels like the right price?','Email','Country','Identity','Select','Woman','Man','Non-binary','Prefer not to say','Saving your vote...','Vote and reserve early access','No payment today. We will only contact you about this founding drop.','Your vote is in. You helped choose the first sample.','We could not save your vote. Please try again.','Gold celestial necklace concept','Fine Chain','Silver Link','Gold vermeil','Recycled 925 silver','United States','North Star','New Moon','Birthstone','Initial','Twin Orbit','Threshold','Quiet Heart','Lucky Four','Solar Disc','Anchor Point','Open Wing','Secret Code','Direction','Beginnings','Origin','Connection','Change','Devotion','Fortune','Confidence','Grounding','Freedom','Private meaning'];
const translations: Record<Exclude<Locale, 'en'>, string[]> = {
zh: ['首发系列 01','概念预览','一起决定首款作品。','你的选择将决定我们的第一批样品。','选择基础链','你的基础链','最多选择五款','你的符号','请至少选择一个符号','首发预估价格','03 / 表达你的选择','你会佩戴这款作品吗？','这是调研概念，并非现货商品。加入候补名单，参与首款样品投票；确认生产后，我们将发送首发消息。','打开完整设计工作室','你认为合适的价格是多少？','电子邮箱','国家或地区','性别','请选择','女性','男性','非二元性别','不愿透露','正在保存投票…','投票并加入候补名单','今天无需付款。我们仅就本次首发与你联系。','投票已保存，感谢你参与首款样品选择。','无法保存投票，请重试。','金色星月项链概念','纤细链','银色链','银镀金','再生925银','美国','北极星','新月','诞生石','姓名首字母','双轨','门槛','静心','幸运四叶','太阳圆盘','锚点','展翼','秘密代码','方向','新起点','起源','联结','改变','挚爱','幸运','自信','安定','自由','私属寓意'],
fr: ['PREMIÈRE COLLECTION 01','Aperçu conceptuel','Choisissez notre première création.','Vos choix façonneront notre premier échantillon.','Choisissez la base','Votre chaîne','Cinq choix maximum','Vos symboles','Choisissez au moins un symbole','Prix de lancement estimé','03 / Votre avis','Porteriez-vous ce bijou ?','Ceci est un concept en cours de recherche, sans stock disponible. Inscrivez-vous pour choisir le premier échantillon et être informé du lancement si nous le produisons.','Ouvrir le studio de création','Quel prix vous semble juste ?','E-mail','Pays','Genre','Choisir','Femme','Homme','Non binaire','Préfère ne pas répondre','Enregistrement…','Voter et rejoindre la liste','Aucun paiement aujourd’hui. Nous vous contacterons uniquement pour cette collection.','Votre vote est enregistré. Merci pour votre participation.','Impossible d’enregistrer votre vote. Réessayez.','Concept de collier céleste doré','Chaîne fine','Maillons argentés','Vermeil','Argent 925 recyclé','États-Unis','Étoile polaire','Nouvelle lune','Pierre de naissance','Initiale','Double orbite','Seuil','Cœur paisible','Trèfle porte-bonheur','Disque solaire','Point d’ancrage','Aile déployée','Code secret','Direction','Commencement','Origine','Lien','Changement','Dévouement','Chance','Confiance','Stabilité','Liberté','Sens personnel'],
es: ['PRIMERA COLECCIÓN 01','Vista conceptual','Elige nuestra primera creación.','Tus elecciones darán forma a nuestra primera muestra.','Elige la base','Tu cadena','Elige hasta cinco','Tus símbolos','Elige al menos un símbolo','Precio de lanzamiento estimado','03 / Tu opinión','¿Te pondrías esta joya?','Este es un concepto en estudio, sin existencias. Únete a la lista para elegir la primera muestra y recibir noticias del lanzamiento si la producimos.','Abrir el estudio de diseño','¿Qué precio te parece justo?','Correo electrónico','País','Género','Seleccionar','Mujer','Hombre','No binario','Prefiero no decirlo','Guardando tu voto…','Votar y unirse a la lista','Hoy no se cobra nada. Solo te contactaremos sobre esta colección.','Tu voto se ha guardado. Gracias por ayudarnos a elegir.','No se pudo guardar el voto. Inténtalo de nuevo.','Concepto de collar celestial dorado','Cadena fina','Eslabones de plata','Vermeil de oro','Plata 925 reciclada','Estados Unidos','Estrella polar','Luna nueva','Piedra natal','Inicial','Órbita doble','Umbral','Corazón sereno','Trébol de la suerte','Disco solar','Punto de anclaje','Ala abierta','Código secreto','Dirección','Comienzos','Origen','Conexión','Cambio','Devoción','Suerte','Confianza','Estabilidad','Libertad','Significado personal'],
de: ['ERSTE KOLLEKTION 01','Konzeptvorschau','Wähle unser erstes Schmuckstück.','Deine Auswahl bestimmt unser erstes Muster.','Wähle die Basis','Deine Kette','Bis zu fünf auswählen','Deine Symbole','Wähle mindestens ein Symbol','Geschätzter Einführungspreis','03 / Deine Meinung','Würdest du das tragen?','Dies ist ein Konzept zur Marktforschung, keine Lagerware. Trage dich ein, wähle das erste Muster mit und erhalte Neuigkeiten, falls wir es produzieren.','Designstudio öffnen','Welcher Preis passt für dich?','E-Mail','Land','Geschlecht','Auswählen','Frau','Mann','Nichtbinär','Keine Angabe','Stimme wird gespeichert…','Abstimmen und vormerken','Heute keine Zahlung. Wir kontaktieren dich nur zu dieser Kollektion.','Deine Stimme ist gespeichert. Danke für deine Auswahl.','Speichern fehlgeschlagen. Bitte erneut versuchen.','Konzept einer goldfarbenen Himmelskette','Feine Kette','Silberglieder','Gold-Vermeil','Recyceltes 925-Silber','Vereinigte Staaten','Nordstern','Neumond','Geburtsstein','Initiale','Doppelorbit','Schwelle','Ruhiges Herz','Glücksklee','Sonnenscheibe','Ankerpunkt','Offener Flügel','Geheimcode','Richtung','Neubeginn','Ursprung','Verbindung','Wandel','Hingabe','Glück','Selbstvertrauen','Halt','Freiheit','Persönliche Bedeutung'],
ja: ['初回コレクション 01','コンセプトプレビュー','最初の作品を一緒に選びましょう。','あなたの選択が最初のサンプルに反映されます。','ベースを選ぶ','ベースチェーン','最大5点まで','あなたのシンボル','1点以上選んでください','発売時の想定価格','03 / あなたの声','このジュエリーを着けたいですか？','これは調査用のコンセプトで、在庫商品ではありません。登録して最初のサンプルに投票すると、製造が決定した場合に発売情報を受け取れます。','デザインスタジオを開く','適切だと思う価格は？','メールアドレス','国・地域','性別','選択してください','女性','男性','ノンバイナリー','回答しない','投票を保存中…','投票して先行案内に登録','本日の支払いはありません。このコレクションについてのみご連絡します。','投票を保存しました。ご協力ありがとうございます。','保存できませんでした。もう一度お試しください。','ゴールドカラーの星月ネックレスのコンセプト','細身チェーン','シルバーリンク','ゴールドヴェルメイユ','再生925シルバー','米国','北極星','新月','誕生石','イニシャル','二つの軌道','扉','穏やかな心','幸運の四つ葉','太陽の円盤','錨','広げた翼','秘密のコード','道しるべ','始まり','ルーツ','つながり','変化','献身','幸運','自信','安定','自由','自分だけの意味'],
ko: ['첫 컬렉션 01','콘셉트 미리보기','첫 작품을 함께 골라 주세요.','여러분의 선택이 첫 샘플에 반영됩니다.','기본 체인 선택','나의 체인','최대 다섯 개 선택','나의 상징','상징을 하나 이상 선택하세요','예상 출시 가격','03 / 의견 남기기','이 주얼리를 착용하고 싶나요?','재고 상품이 아닌 시장 조사용 콘셉트입니다. 대기 명단에 등록하여 첫 샘플에 투표하고, 제작이 결정되면 출시 소식을 받아 보세요.','디자인 스튜디오 열기','어떤 가격이 적당한가요?','이메일','국가','성별','선택','여성','남성','논바이너리','응답하지 않음','투표 저장 중…','투표하고 사전 알림 신청','오늘 결제는 없습니다. 이 컬렉션에 관해서만 연락드립니다.','투표가 저장되었습니다. 참여해 주셔서 감사합니다.','투표를 저장하지 못했습니다. 다시 시도해 주세요.','금빛 별과 달 목걸이 콘셉트','가는 체인','실버 링크','골드 버메일','재활용 925 실버','미국','북극성','초승달','탄생석','이니셜','이중 궤도','문턱','고요한 마음','행운의 네잎','태양 원반','닻','펼친 날개','비밀 코드','방향','시작','기원','연결','변화','헌신','행운','자신감','안정','자유','나만의 의미'],
ar: ['المجموعة الأولى 01','معاينة التصور','اختاري أول قطعة نصنعها.','اختياراتك ستحدد أول عينة إنتاج.','اختاري الأساس','سلسلتك','اختاري حتى خمس قطع','رموزك','اختاري رمزًا واحدًا على الأقل','سعر الإطلاق التقديري','03 / شاركي رأيك','هل ترغبين في ارتداء هذه القطعة؟','هذا تصور بحثي وليس منتجًا متوفرًا. انضمي إلى القائمة للتصويت على أول عينة وتلقي أخبار الإطلاق إذا قررنا إنتاجها.','افتحي استوديو التصميم','ما السعر المناسب برأيك؟','البريد الإلكتروني','البلد','النوع الاجتماعي','اختيار','امرأة','رجل','غير ثنائي','أفضل عدم الإفصاح','جارٍ حفظ التصويت…','صوّتي وانضمي إلى القائمة','لا يوجد دفع اليوم. سنتواصل معك بخصوص هذه المجموعة فقط.','تم حفظ تصويتك. شكرًا لمساعدتنا في اختيار العينة.','تعذر حفظ التصويت. حاولي مرة أخرى.','تصور لقلادة سماوية ذهبية اللون','سلسلة رفيعة','حلقات فضية','فضة مطلية بالذهب','فضة 925 معاد تدويرها','الولايات المتحدة','نجم الشمال','قمر جديد','حجر الميلاد','الحرف الأول','مدار مزدوج','عتبة','قلب هادئ','برسيم الحظ','قرص الشمس','نقطة ارتكاز','جناح مفتوح','رمز سري','الاتجاه','البدايات','الأصل','الترابط','التغيير','الإخلاص','الحظ','الثقة','الثبات','الحرية','معنى شخصي'],
};

export function foundingCopy(locale: Locale) {
  const values = locale === 'en' ? en : translations[locale];
  if (values.length !== en.length) throw new Error(`Incomplete founding-drop locale: ${locale}`);
  const dictionary = new Map(en.map((key, index) => [key, values[index]]));
  dictionary.set('Personal identity', {en:'Identity', zh:'身份', fr:'Identité', es:'Identidad', de:'Identität', ja:'自分らしさ', ko:'정체성', ar:'الهوية'}[locale]);
  return (key: string) => dictionary.get(key) ?? key;
}
